OpenNebula:
  credentials: 'oneadmin:81c7d48de47166de4695c16c96b5d66db34c981c' # oneadmin and password(or auth-token) for oneadmin
  endpoint: 'http://localhost:2633/RPC2' # RPC endpoint for OpenNebula
  users-group: 1 # Main group for Basic Users
  users-vms-ssh-port: 52222 # Default SSH-port at VMs instantiated from your templates
  default-node-id: 0 # ID of the node, vms to deploy by default
  base-vnc-port: 5900 # Base VNC-port number. VMs will get port for VNC by formula: {{ base-vnc-port }} + {{ vmid }}

Server:
  # Port for WHMConnector to listen
  listen-port: '8008'
  # Delay value for trial VMs in seconds
  trial-suspend-delay: 14400

Include: # IONe libraries to include
  - 'vmcontrol'
  - 'vminfo'
  - 'server'
  - 'data_import_handler'
  - 'useful_things'
  - 'creative_funcs'

Modules: # IONe modules to connect
  - 'std++'
  - 'whmcscall'
  - 'ansible'
  - 'freenas'
  - 'stat'
  - 'webapi'
  - 'updatesmanager'
#  - 'telegrambot'

Scripts: # Automation scripts to start
  - 'snap-controller'

vCenter:
  cpu-limits-koef: 2000

SnapshotController:
  check-period: 3600 # Snapshots check frequency in seconds

Other:
  debug: false
  debug-modules:
    - 'std++'
    - 'whmcscall'
    - 'ansible'
    - 'freenas'
    - 'stat'
  
  key: false
