OpenNebula:
  credentials: 'oneadmin:Nhb500Gznmcjn' # oneadmin and password(or auth-token) for oneadmin
  endpoint: 'http://localhost:2633/RPC2' # RPC endpoint for OpenNebula
  users-group: 1 # Main group for Basic Users
  users-vms-ssh-port: 52222 # Default SSH-port at VMs instantiated from your templates
  default-node-id: 0 # ID of the node, vms to deploy by default
  base-vnc-port: 5900 # Base VNC-port number. VMs will get port for VNC by formula: {{ base-vnc-port }} + {{ vmid }}
  reinstall-template-id: 35

AnsibleServer: # Credentials for Ansible Server
  active: true
  host: '185.66.69.101'
  port: 52222
  user: 'root'
  password: 'So8ghgOdQFpcecE'
  data-getters-url: '/scripts/server/service/ansible/getters.rb'

WHMCS: # Credentials for connection with WHMCS
  uri: 'https://my.support.by/includes/api.php' # API script
  # Credentials
  username: 'hell_api'
  password: '3924105f27ca00fd90a08aadddfb65e9'
  # Port for WHMConnector to listen
  listen-port: '8008'
  # Delay value for trial VMs in seconds
  trial-suspend-delay: 14400

Include:
  - 'std++'
Other:
  debug: true