OpenNebula:
  credentials: 'oneadmin:secret' # oneadmin and password(or auth-token) for oneadmin
  endpoint: 'http://localhost:2633/RPC2' # RPC endpoint for OpenNebula
  users-group: 1 # Main group for Basic Users
  users-vms-ssh-port: 22 # Default SSH-port at VMs instantiated from your templates
  default-node-id: 0 # ID of the node, vms to deploy by default
  base-vnc-port: 5900 # Base VNC-port number. VMs will get port for VNC by formula: {{ base-vnc-port }} + {{ vmid }}
  reinstall-template-id: 35

AnsibleServer: # Credentials for Ansible Server
  active: true
  host: 'addr'
  port: 22
  user: 'root'
  password: 'Secret1111'
  data-getters-url: '/scripts/server/service/ansible/getters.rb'

WHMCS: # Credentials for connection with WHMCS
  uri: 'https://whmcs.your.domain/includes/api.php' # API script
  # Credentials
  username: 'api'
  password: 'token'
  # Port for WHMConnector to listen
  listen-port: '8008'
  # Delay value for trial VMs in seconds
  trial-suspend-delay: 14400

Other:
  debug: true
