UpdatesManager:
  update: true # Will not update anything if false
  autoupdate-on-startup: true # Checks updates on server startup if true
  
  repo: 'https://slnt_opp:Jago322==@bitbucket.org/slnt_opp/ione-cloud.git' # Git repo supported URL to %reponame%.git
  branch: 'stable' # Branch, where get updates

  update-token: "up5Bxkoma9lnM"